import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../data/repositories/social_repository.dart';
import 'profile_screen.dart';
import '../../bloc/room_cubit.dart';
import '../rooms/room_lobby_screen.dart';

class OnlineUsersScreen extends StatefulWidget { const OnlineUsersScreen({super.key}); @override State<OnlineUsersScreen> createState()=>_OnlineUsersScreenState(); }
class _OnlineUsersScreenState extends State<OnlineUsersScreen>{
  late Future<Map<String,dynamic>> _future;
  @override void initState(){super.initState();_future=_load();}
  Future<Map<String,dynamic>> _load()=>context.read<SocialRepository>().onlineUsers();
  void _reload()=>setState(()=>_future=_load());
  Future<void> _actions(Map<String,dynamic> u) async {final id=(u['id'] as num?)?.toInt();if(id==null)return;final a=await showModalBottomSheet<String>(context:context,builder:(c)=>SafeArea(child:ListView(shrinkWrap:true,children:[ListTile(title:Text('${u['display_name']??u['username']??''}'),enabled:false),ListTile(title:const Text('الملف الشخصي'),onTap:()=>Navigator.pop(c,'profile')),if(u['is_friend']!=true)ListTile(title:const Text('إرسال طلب صداقة'),onTap:()=>Navigator.pop(c,'friend')),ListTile(title:const Text('إرسال رسالة'),onTap:()=>Navigator.pop(c,'message')),ListTile(title:const Text('حظر'),onTap:()=>Navigator.pop(c,'block')),if(u['room_id']!=null&&u['room_private'] != true)ListTile(title:const Text('انضمام إلى الطاولة'),onTap:()=>Navigator.pop(c,'join'))])));if(!mounted||a==null)return;try{switch(a){case'profile':final d=await context.read<SocialRepository>().profile(id);if(mounted)await Navigator.push(context,MaterialPageRoute(builder:(_)=>ProfileScreen(userId:id,initialData:d)));break;case'friend':await context.read<SocialRepository>().sendFriendRequest(id);break;case'message':final t=TextEditingController();try{await showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('رسالة'),content:TextField(controller:t,maxLines:4),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),ElevatedButton(onPressed:()async{if(t.text.trim().isNotEmpty){await context.read<SocialRepository>().message(id,t.text.trim());if(c.mounted)Navigator.pop(c);}},child:const Text('إرسال'))]));}finally{t.dispose();}break;case'block':await context.read<SocialRepository>().block(id);break;case'join': final roomId='${u['room_id']}'; context.read<RoomCubit>().enterRoom(roomId); if(mounted)await Navigator.push(context,MaterialPageRoute(builder:(_)=>const RoomLobbyScreen())); break;}_reload();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر تنفيذ العملية: $e')));}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المتصلون'),actions:[IconButton(onPressed:_reload,icon:const Icon(Icons.refresh),tooltip:'تحديث')]),body:FutureBuilder<Map<String,dynamic>>(future:_future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('تعذر تحميل المتصلين: ${s.error}'));final rows=s.data?['users'] as List? ?? const [];if(rows.isEmpty)return const Center(child:Text('لا يوجد مستخدمون متصلون الآن'));return RefreshIndicator(onRefresh:()async=>_reload(),child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final u=Map<String,dynamic>.from(rows[i] as Map);return ListTile(onTap:()=>_actions(u),title:Text('${u['display_name']??u['username']??'مستخدم'}'),subtitle:Text('@${u['username']??''}${u['in_table']==true?' — داخل طاولة ${u['game']??''}':''}'));}));}));
}
